apiVersion: v1
kind: Pod
metadata:
  name: test-shell
spec:
  containers:
  - name: alpine
    image: alpine
    # Just sleep forever
    command: [ "tail" ]
    args: [ "-f", "/dev/null" ]
  restartPolicy: Always
